apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://10.0.1.147:6443
    insecure-skip-tls-verify: true
  name: default
users:
- name: admin
  user:
    token: K10c0b52ca2d3c0bb17feaf5f7942f6969de50372f904a1dae2f209e00217d8fea3::server:fafba08d1ba0f340801f1916d4f0631c
contexts:
- context:
    cluster: default
    user: admin
  name: default
current-context: default
